const express = require('express');
const cors = require('cors');

const app = express();
app.use(cors());
app.use(express.json({ limit: '5mb' }));

const HF_API = process.env.HUGGINGFACE_API_KEY;
const HF_MODEL = process.env.HUGGINGFACE_MODEL || 'gpt2';

app.get('/health', (req, res) => res.json({ ok: true }));

app.post('/generate', async (req, res) => {
  try {
    const { prompt = 'Create a marketing update for Mescript Labs.', context = '' } = req.body || {};

    if (!HF_API) {
      // Return a simple structured draft if no HF key present
      const title = `AI Draft: ${prompt.split(' ').slice(0,6).join(' ')}`;
      return res.json({ title, summary: `Fallback summary for ${context}`, body: `Fallback body: ${prompt}`, suggestions: ['Refine tone', 'Add CTA'] });
    }

    const model = HF_MODEL;
    const hfResp = await fetch(`https://api-inference.huggingface.co/models/${model}`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${HF_API}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ inputs: `Create a concise marketing draft for: ${prompt}. Context: ${context}`, options: { wait_for_model: true } })
    });

    if (!hfResp.ok) {
      const txt = await hfResp.text();
      console.error('HF inference error', hfResp.status, txt);
      return res.status(502).json({ error: 'Hugging Face inference error', details: txt });
    }

    const text = await hfResp.text();
    let parsed = null;
    try { parsed = JSON.parse(text); } catch (e) { parsed = null; }

    // Extract generated text heuristically
    const body = parsed?.generated_text || (Array.isArray(parsed) && parsed[0]?.generated_text) || text;
    const title = `AI Draft: ${prompt.split(' ').slice(0,6).join(' ')}`;
    const summary = `Generated by model ${model}`;
    const suggestions = ['Review & refine', 'Add product specifics', 'Check tone and CTAs'];

    return res.json({ title, summary, body, suggestions });
  } catch (err) {
    console.error('Generate error', err);
    return res.status(500).json({ error: 'Server error' });
  }
});

const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`Render backend listening on ${port}`));
