from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional, List
import os
import httpx

app = FastAPI(title="Mescript Labs Render AI Proxy")

HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACE_API_KEY")
HUGGINGFACE_MODEL = os.getenv("HUGGINGFACE_MODEL", "gpt2")


class GenerateRequest(BaseModel):
    prompt: Optional[str] = "Create a marketing update for Mescript Labs."
    context: Optional[str] = None


class GenerateResponse(BaseModel):
    title: str
    summary: str
    body: str
    suggestions: List[str]


@app.get("/health")
async def health():
    return {"ok": True}


@app.post("/generate", response_model=GenerateResponse)
async def generate(req: GenerateRequest):
    prompt = req.prompt or "Create a marketing update for Mescript Labs."
    context = req.context or ""

    if not HUGGINGFACE_API_KEY:
        title = f"AI Draft: {' '.join(prompt.split()[:6])}"
        return GenerateResponse(
            title=title,
            summary=f"Fallback summary for {context}",
            body=f"Fallback body: {prompt}",
            suggestions=["Refine tone", "Add CTA"],
        )

    model = HUGGINGFACE_MODEL
    url = f"https://api-inference.huggingface.co/models/{model}"
    headers = {"Authorization": f"Bearer {HUGGINGFACE_API_KEY}", "Content-Type": "application/json"}

    payload = {"inputs": f"Create a concise marketing draft for: {prompt}. Context: {context}", "options": {"wait_for_model": True}}

    async with httpx.AsyncClient(timeout=60.0) as client:
        resp = await client.post(url, headers=headers, json=payload)
        if resp.status_code != 200:
            text = await resp.aread()
            raise HTTPException(status_code=502, detail=f"Hugging Face inference error: {resp.status_code} {text}")

        text = await resp.aread()
        # Try to parse JSON; otherwise use raw text
        body_text = None
        try:
            parsed = resp.json()
            if isinstance(parsed, dict) and "generated_text" in parsed:
                body_text = parsed["generated_text"]
            elif isinstance(parsed, list) and parsed and isinstance(parsed[0], dict) and "generated_text" in parsed[0]:
                body_text = parsed[0]["generated_text"]
            else:
                # some models return plain text
                body_text = resp.text
        except Exception:
            body_text = resp.text

    title = f"AI Draft: {' '.join(prompt.split()[:6])}"
    summary = f"Generated by model {model}"
    suggestions = ["Review & refine", "Add product specifics", "Check tone and CTAs"]

    return GenerateResponse(title=title, summary=summary, body=body_text, suggestions=suggestions)
